language: python
python:
- '2.7'
script: ./setup.py nosetests
branches:
  only:
  - master
  - dev
deploy:
  provider: pypi
  user: gurunars
  on:
    branch: master
  password:
    secure: L9TWyUBZ+nUXf+s3fRoa+IEqev/dhhr9sM+OIuODsnegd/sNvPsUTpr2pZoMil/R7zJXGm+xh0Pz/RD7FyDH/YIX1IJksqIyDn0C6L6I6oVqoBredemaoWbdvsy0hiditpd9KJg3N3GLaIW+pxiBJ6sPH+0zeWsYb+PwOuHccr8=
