language: python
python:
- '2.7'
script: ./setup.py nosetests
branches:
  only:
  - master
  - dev
deploy:
  provider: pypi
  user: gurunars
  on:
    branch: master
  password:
    secure: V6SnUvJVDBCCbcHT+t0NjZA7PrgaZNMjP0BYsFS4xid+U0RX+g/MpdcHJK/NWK/ZqY6EdmCQLbQn/M79UhIHTllta2wLrnUa7YkqjVkUkdGkjf9/Ki2PDS607mmGZxYZ4qIOCt6yS590iSoh/QZ6Gykc6LVkO3aZx8C64H+YIig=
