language: python
python:
- '2.7'
script: ./setup.py nosetests
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-tk
deploy:
  provider: pypi
  user: gurunars
  on:
    branch: master
  password:
    secure: VOlpaICOkhyxiMUOctf8SV3jXIcv4cBHchxrk0ylXAKcw5HU1x0zgsA/5C46KKgtRZzgHie56VnKZ+G8wYz9rYEEfqJIHyy6lUqS9UXF3tmpHk3jbWMgdEYg6J3sdx5/coWmkVs1uGExoUpN5WEJllUrgSlbbaVwu76cKs/alQc=
